# Generated by Django 4.2.1 on 2023-08-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_gotten_code",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_gotten_code_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
