# Generated by Django 4.2.1 on 2023-08-16 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_last_gotten_code_user_last_gotten_code_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_first_time",
        ),
    ]
