# Generated by Django 4.2.1 on 2023-08-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_is_first_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="deep_link",
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="Deep Link"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен?"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="Админ?"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_blocked_bot",
            field=models.BooleanField(default=False, verbose_name="Заблокировал бота?"),
        ),
        migrations.AlterField(
            model_name="user",
            name="language_code",
            field=models.CharField(
                blank=True, default="ru", max_length=8, null=True, verbose_name="Язык"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_gotten_code",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="Последний полученный код",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_gotten_code_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время получения последнего кода"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(max_length=32, unique=True, verbose_name="Телеграм ID"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="Телеграм Username"
            ),
        ),
    ]
