# Generated by Django 4.2.1 on 2023-09-22 12:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_last_gotten_code_phrase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_gotten_code_phrase",
        ),
    ]
