# Generated by Django 4.2.1 on 2023-08-16 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Code",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("phrase", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("max_uses", models.IntegerField(default=0)),
                ("uses", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UniqueCode",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "phrase_code",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="codes.code"),
                ),
            ],
        ),
    ]
