# Generated by Django 4.2.1 on 2023-08-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uniquecode",
            name="is_active",
        ),
        migrations.AddField(
            model_name="uniquecode",
            name="used",
            field=models.BooleanField(default=False),
        ),
    ]
