# Generated by Django 4.2.1 on 2023-12-24 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_user_last_gotten_code_phrase"),
        ("codes", "0006_alter_code_conditions_alter_code_instructions"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "fileid",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="ID файла"
                    ),
                ),
                (
                    "file_unique_id",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Уникальный Telegram ID файла",
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(default=False, verbose_name="Принят?"),
                ),
                (
                    "gift_type",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Тип подарка",
                    ),
                ),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="Обработан?"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Обработан в"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан в"),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processed_by",
                        to="users.user",
                        verbose_name="Обработал",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.user",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос на проверку чека",
                "verbose_name_plural": "Запросы на проверку чека",
                "ordering": ("-created_at",),
            },
        ),
    ]
