# Generated by Django 4.2.1 on 2023-12-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codes", "0008_alter_checkrequest_accepted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniqueGiftCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Уникальный код"
                    ),
                ),
                ("gift_type", models.SmallIntegerField()),
                (
                    "used",
                    models.BooleanField(default=False, verbose_name="Использован?"),
                ),
            ],
            options={
                "verbose_name": "Уникальный код подарка",
                "verbose_name_plural": "Уникальные коды подарков",
            },
        ),
        migrations.AddField(
            model_name="checkrequest",
            name="message_id",
            field=models.CharField(
                default="", max_length=255, unique=True, verbose_name="ID сообщения"
            ),
            preserve_default=False,
        ),
    ]
