# Generated by Django 4.2.1 on 2023-12-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codes", "0009_uniquegiftcode_checkrequest_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkrequest",
            name="message_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID сообщения"
            ),
        ),
    ]
