# Generated by Django 4.2.1 on 2023-08-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ButtonText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(choices=[], max_length=255, unique=True)),
                ("text", models.TextField(max_length=5000)),
            ],
            options={
                "db_table": "button_text_table",
            },
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("disabled_for_new_users", "disabled_for_new_users"),
                            ("start", "start"),
                            ("user_error_message", "user_error_message"),
                        ],
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("text", models.TextField(max_length=5000)),
            ],
            options={
                "db_table": "text_table",
            },
        ),
    ]
