# Generated by Django 4.2.1 on 2023-12-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("text_manager", "0007_alter_text_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="text",
            name="title",
            field=models.CharField(
                choices=[
                    ("code_not_found", "code_not_found"),
                    ("code_successfully_gotten", "code_successfully_gotten"),
                    ("disabled_for_new_users", "disabled_for_new_users"),
                    ("image_already_sent", "image_already_sent"),
                    ("image_successfully_gotten", "image_successfully_gotten"),
                    ("same_code_too_early", "same_code_too_early"),
                    ("start", "start"),
                    ("unique_code_not_found", "unique_code_not_found"),
                    ("user_error_message", "user_error_message"),
                ],
                max_length=255,
                unique=True,
                verbose_name="Название",
            ),
        ),
    ]
